#instull_services.yml
---
  - hosts: haproxy
    become: true
    tasks:
      - name: Installing apache
        apt: name=apache2 state=latest
      - name: Ensure apache starts
        service: name=apache2 state=started enabled=yes

  - hosts: webservers
    become: true
    tasks:
      - name: Inastalling services
        apt:
          name:
             - apache2
             - php 
             - libapache2-mod-php
      - name: Ensure services starts
        service: name=apache2 state=started enabled=yes
