#setup-app.yml
---
  - hosts: webservers
    become: true
    tasks:
     - name: Upload application file
       copy:
          src: ../index.php
          dest: /var/www/html
          mode: 0755

     - name: Onfigure hph.ini file
       lineinfile:
             path: /etc/php/7.4/apache2/php.ini
             regexp: ^short_open_tag
             line: 'short_open_tag=On'

     - name: Testart apache
       service: name=apache2 state=restarted












